name: Build ISO
on: [push]

jobs:
  build:
    name: Build ISO file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build ISO
        run: docker-compose up
      - run: ls ./
      - run: ls ./dist
      - name: Rename ISO (Hack)
        run: mv dist/archlinux-*.iso dist/archlinux.iso
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: archlinux.iso
          path: ./dist/archlinux.iso
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload GitHub release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/archlinux.iso
          asset_name: archlinux.iso
          asset_content_type: application/octet-stream