name: Build ISO
on: [push]

jobs:
  build:
    name: Build ISO file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build ISO
        run: docker-compose up
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: iso
          path: out